# DB Config
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpadb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver


# Jpa Config
  jpa:
    hibernate:
      ddl-auto: update 
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        